"""
Application configuration following the XDG Base Directory Specification.

Config file:   $XDG_CONFIG_HOME/tui-trader/config.env
               (default: ~/.config/tui-trader/config.env)

Data directory: $XDG_DATA_HOME/tui-trader/
               (default: ~/.local/share/tui-trader/)
               Contains: trades.db

On first run, if no config file exists, a template is created at the config
path and the app exits with instructions to fill in API credentials.
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv


# ---------------------------------------------------------------------------
# XDG paths
# ---------------------------------------------------------------------------

def get_config_dir() -> Path:
    """Return $XDG_CONFIG_HOME/tui-trader, defaulting to ~/.config/tui-trader."""
    xdg_config = os.environ.get("XDG_CONFIG_HOME", "")
    base = Path(xdg_config) if xdg_config else Path.home() / ".config"
    return base / "tui-trader"


def get_data_dir() -> Path:
    """Return $XDG_DATA_HOME/tui-trader, defaulting to ~/.local/share/tui-trader."""
    xdg_data = os.environ.get("XDG_DATA_HOME", "")
    base = Path(xdg_data) if xdg_data else Path.home() / ".local" / "share"
    return base / "tui-trader"


CONFIG_DIR = get_config_dir()
DATA_DIR = get_data_dir()
CONFIG_FILE = CONFIG_DIR / "config.env"
DATABASE_PATH = DATA_DIR / "trades.db"


# ---------------------------------------------------------------------------
# First-run bootstrap
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# tui-trader configuration
# Generated by tui-trader. Edit this file to configure the application.

# Kraken API credentials
# Generate at: https://www.kraken.com/u/security/api
# Required permissions: Query Funds, Query/Create/Cancel Orders, Query Trades
KRAKEN_API_KEY=your_api_key_here
KRAKEN_API_SECRET=your_api_secret_here

# Default trading pair to show on startup
DEFAULT_SYMBOL=BTC/USD

# History screen REST refresh interval (seconds)
HISTORY_REFRESH_SECONDS=60

# WebSocket reconnect backoff (seconds)
WS_RECONNECT_BACKOFF=5

# Risk management: default stop-loss percentage
DEFAULT_STOP_LOSS_PCT=2.0

# Order book depth (must be one of: 10, 25, 100, 500, 1000)
ORDER_BOOK_DEPTH=10
"""


def _bootstrap_config() -> None:
    """Create config directory and template file if they don't exist."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if not CONFIG_FILE.exists():
        CONFIG_FILE.write_text(_CONFIG_TEMPLATE)
        print(f"Config file created at: {CONFIG_FILE}")
        print("Please add your Kraken API credentials and re-run tui-trader.")
        sys.exit(0)


def _bootstrap_data() -> None:
    """Create data directory if it doesn't exist."""
    DATA_DIR.mkdir(parents=True, exist_ok=True)


# Run bootstrap and load config on import
_bootstrap_config()
_bootstrap_data()
load_dotenv(CONFIG_FILE)


# ---------------------------------------------------------------------------
# Config helpers
# ---------------------------------------------------------------------------

def _require(key: str) -> str:
    value = os.getenv(key)
    if not value or value == f"your_{key.lower()}_here":
        raise EnvironmentError(
            f"'{key}' is not configured.\n"
            f"Edit {CONFIG_FILE} and add your Kraken API credentials."
        )
    return value


def _get_float(key: str, default: float) -> float:
    try:
        return float(os.getenv(key, str(default)))
    except ValueError:
        return default


def _get_int(key: str, default: int) -> int:
    try:
        return int(os.getenv(key, str(default)))
    except ValueError:
        return default


# ---------------------------------------------------------------------------
# Settings
# ---------------------------------------------------------------------------

# --- Kraken credentials ---
KRAKEN_API_KEY: str = _require("KRAKEN_API_KEY")
KRAKEN_API_SECRET: str = _require("KRAKEN_API_SECRET")

# --- Trading defaults ---
DEFAULT_SYMBOL: str = os.getenv("DEFAULT_SYMBOL", "BTC/USD")

# --- Refresh / timing ---
HISTORY_REFRESH_SECONDS: int = _get_int("HISTORY_REFRESH_SECONDS", 60)
WS_RECONNECT_BACKOFF: float = _get_float("WS_RECONNECT_BACKOFF", 5.0)

# --- Risk management ---
DEFAULT_STOP_LOSS_PCT: float = _get_float("DEFAULT_STOP_LOSS_PCT", 2.0)

# --- Order book ---
_VALID_BOOK_DEPTHS = {10, 25, 100, 500, 1000}
_raw_depth = _get_int("ORDER_BOOK_DEPTH", 10)
ORDER_BOOK_DEPTH: int = _raw_depth if _raw_depth in _VALID_BOOK_DEPTHS else 10
